/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas;

import Logica.Utilitario;
import Modelos.Album;
import Modelos.Artista;
import Modelos.Cancion;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class dialogCanciones extends javax.swing.JDialog {
   
    DefaultListModel modeloListaCanciones = new DefaultListModel();
    
    //Variable para verificar si el usuario está usando el botón "Modificar"
    private boolean modificando = false; 
    
    //Variable de instancia para almacenar el Artista actual
    private Cancion cancionActual;
    private Album albumActual;
    private Album albumAnterior;
    

    /**
     * Creates new form dialogArtistas
     */
    public dialogCanciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        lstCanciones.setModel(modeloListaCanciones);
        actualizarListaCanciones();
        limpiarCajas();
        frameEditarCancion.setVisible(false);
        
    }

    private dialogCanciones(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstCanciones = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        paneInfoCancion = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        txtGrabacionConsultar = new javax.swing.JTextField();
        txtTituloCancionConsultar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDuracionConsultar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreArtistaConsultar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroCancionConsultar = new javax.swing.JTextField();
        txtAutorConsultar = new javax.swing.JTextField();
        txtAlbumConsultar = new javax.swing.JTextField();
        frameEditarCancion = new javax.swing.JInternalFrame();
        txtDuracion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtGrabacion = new javax.swing.JTextField();
        txtTituloCancion = new javax.swing.JTextField();
        txtNumeroCancion = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbAlbumes = new javax.swing.JComboBox<>();
        txtAutor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(856, 638));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 684, -1, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnInsertar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnInsertar.setPreferredSize(new java.awt.Dimension(98, 23));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -50, 15, 861));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(98, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 98, -1));

        lstCanciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCancionesMouseClicked(evt);
            }
        });
        lstCanciones.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCancionesValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstCanciones);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 275, 157));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Canciones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 275, -1));

        paneInfoCancion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Autor");

        txtGrabacionConsultar.setEditable(false);
        txtGrabacionConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtGrabacionConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrabacionConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrabacionConsultarActionPerformed(evt);
            }
        });

        txtTituloCancionConsultar.setEditable(false);
        txtTituloCancionConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtTituloCancionConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTituloCancionConsultar.setPreferredSize(new java.awt.Dimension(135, 22));
        txtTituloCancionConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloCancionConsultarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Año de Grabación");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtDuracionConsultar.setEditable(false);
        txtDuracionConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtDuracionConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDuracionConsultar.setPreferredSize(new java.awt.Dimension(135, 22));
        txtDuracionConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionConsultarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Artista de la Canción");

        txtNombreArtistaConsultar.setEditable(false);
        txtNombreArtistaConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreArtistaConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreArtistaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArtistaConsultarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Título");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Album de la Canción");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Número");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Duración");

        txtNumeroCancionConsultar.setEditable(false);
        txtNumeroCancionConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroCancionConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroCancionConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCancionConsultarActionPerformed(evt);
            }
        });

        txtAutorConsultar.setEditable(false);
        txtAutorConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtAutorConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAutorConsultar.setPreferredSize(new java.awt.Dimension(135, 22));
        txtAutorConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorConsultarActionPerformed(evt);
            }
        });

        txtAlbumConsultar.setEditable(false);
        txtAlbumConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtAlbumConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlbumConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlbumConsultarActionPerformed(evt);
            }
        });

        paneInfoCancion.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(txtGrabacionConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(txtTituloCancionConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(txtDuracionConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(txtNombreArtistaConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(txtNumeroCancionConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(txtAutorConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneInfoCancion.setLayer(txtAlbumConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneInfoCancionLayout = new javax.swing.GroupLayout(paneInfoCancion);
        paneInfoCancion.setLayout(paneInfoCancionLayout);
        paneInfoCancionLayout.setHorizontalGroup(
            paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInfoCancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInfoCancionLayout.createSequentialGroup()
                        .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreArtistaConsultar))
                        .addGap(18, 18, 18)
                        .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneInfoCancionLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAlbumConsultar)))
                    .addGroup(paneInfoCancionLayout.createSequentialGroup()
                        .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDuracionConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumeroCancionConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGrabacionConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTituloCancionConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAutorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        paneInfoCancionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel7, txtNombreArtistaConsultar, txtNumeroCancionConsultar, txtTituloCancionConsultar});

        paneInfoCancionLayout.setVerticalGroup(
            paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInfoCancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInfoCancionLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInfoCancionLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreArtistaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCancionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloCancionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInfoCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneInfoCancionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuracionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInfoCancionLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAutorConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrabacionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneInfoCancionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel5, jLabel7, txtNombreArtistaConsultar, txtNumeroCancionConsultar, txtTituloCancionConsultar});

        jPanel1.add(paneInfoCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        frameEditarCancion.setVisible(true);

        txtDuracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDuracion.setPreferredSize(new java.awt.Dimension(135, 22));
        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Año de Grabación");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Album de la Canción");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Autor");

        txtGrabacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrabacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrabacionActionPerformed(evt);
            }
        });

        txtTituloCancion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTituloCancion.setPreferredSize(new java.awt.Dimension(135, 22));
        txtTituloCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloCancionActionPerformed(evt);
            }
        });

        txtNumeroCancion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCancionActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Título");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Duración");

        for (Artista artista : Utilitario.listaArtistas) {
            for (Album album : artista.getListaAlbumes()){
                cmbAlbumes.addItem(album.getNombre());
            }
        }

        txtAutor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAutor.setPreferredSize(new java.awt.Dimension(135, 22));
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Número");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameEditarCancionLayout = new javax.swing.GroupLayout(frameEditarCancion.getContentPane());
        frameEditarCancion.getContentPane().setLayout(frameEditarCancionLayout);
        frameEditarCancionLayout.setHorizontalGroup(
            frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEditarCancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameEditarCancionLayout.createSequentialGroup()
                        .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGrabacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumeroCancion))
                        .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameEditarCancionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTituloCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEditarCancionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbAlbumes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(frameEditarCancionLayout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        frameEditarCancionLayout.setVerticalGroup(
            frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEditarCancionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameEditarCancionLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameEditarCancionLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameEditarCancionLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameEditarCancionLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(frameEditarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(frameEditarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Eliminar artista seleccionado de la lista
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //artistaSeleccionado();
        eliminarCancion(cancionActual);
        actualizarListaCanciones();
        limpiarCajas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTituloCancionConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloCancionConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloCancionConsultarActionPerformed
    
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        paneInfoCancion.setVisible(false);
        frameEditarCancion.setVisible(true);
        modificando = false;
        limpiarCajas();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        paneInfoCancion.setVisible(false);
        frameEditarCancion.setVisible(true);
        modificando = true;
        editarInfoCancion(cancionActual);
        albumAnterior(); 
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtNumeroCancionConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCancionConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCancionConsultarActionPerformed

    private void lstCancionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCancionesValueChanged
    }//GEN-LAST:event_lstCancionesValueChanged

    private void lstCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCancionesMouseClicked
        cancionSeleccionada();
        obtenerInfoCancion(cancionActual);
        editarInfoCancion(cancionActual);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_lstCancionesMouseClicked

    private void txtNombreArtistaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArtistaConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArtistaConsultarActionPerformed

    private void txtDuracionConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionConsultarActionPerformed

    private void txtAutorConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorConsultarActionPerformed

    private void txtGrabacionConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrabacionConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrabacionConsultarActionPerformed

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void txtTituloCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloCancionActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtNumeroCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCancionActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        albumSeleccionado();
        if (modificando == true) { //Verifica si el usuario está usando el botón de modificar
           modificarCancion(cancionActual);
        } else {
            agregarCancion(albumActual);
        }
        actualizarListaCanciones();
        deshabilitarCajas();
        modificando = false;  
        frameEditarCancion.dispose();
        paneInfoCancion.setVisible(true);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtGrabacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrabacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrabacionActionPerformed

    private void txtAlbumConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlbumConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumConsultarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        frameEditarCancion.dispose();
        paneInfoCancion.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    
    
    
    //Muestra y actualiza la lista en la interfaz sin necesidad de cerrar la ventana, y que pueda ser invocado cuando sea necesario
    private void actualizarListaCanciones(){
        modeloListaCanciones.clear(); //Limpiar la lista visualmente antes de volver a cargarla, evitando el duplicado visual de informacion
        for (Artista artista : Utilitario.listaArtistas) {
            for (Album album : artista.getListaAlbumes()) {
               modeloListaCanciones.addAll(album.generarListaCanciones());  
            } 
        }
    }
    
    //Toma el indice seleccionado de la lista Canciones
    private void cancionSeleccionada(){
        String nombreCancion = lstCanciones.getSelectedValue();
        if (nombreCancion != null) {
            for (Artista artista : Utilitario.listaArtistas) {
                for (Album album : artista.getListaAlbumes()) {
                    for (Cancion cancion : album.getListaCanciones()) {
                       if (cancion.getTitulo().equals(nombreCancion)) {
                           this.cancionActual = cancion; 
                           this.albumActual = album;
                        }
                    }
                }
            }
        }
    }
    
    //Toma el indice seleccionado del ComboBox Albumes
    private void albumSeleccionado(){
        Object nombreAlbum = cmbAlbumes.getSelectedItem();
        if (nombreAlbum != null) {
            for (Artista artista : Utilitario.listaArtistas) {
                for (Album album : artista.getListaAlbumes()) {
                    if (album.getNombre().equals(nombreAlbum)) {
                    this.albumActual = album;
                    }
                }
            }
        }
    }
    
    //Toma el indice seleccionado del ComboBox Albumes para guardarlo en una variable temporal
    private void albumAnterior(){
        Object nombreAlbum = cmbAlbumes.getSelectedItem();
        if (nombreAlbum != null) {
            for (Artista artista : Utilitario.listaArtistas) {
                for (Album album : artista.getListaAlbumes()) {
                    if (album.getNombre().equals(nombreAlbum)) {
                    this.albumAnterior = album;
                    }   
                }
            }
        }
    }
    
    //Obtiene los datos de una canción y los muestra en las cajas de texto respectivas
    private void obtenerInfoCancion(Cancion cancion){
       txtNumeroCancionConsultar.setText(Integer.toString(cancion.getNumero()));
       txtTituloCancionConsultar.setText(cancion.getTitulo());
       txtNombreArtistaConsultar.setText(albumActual.getMapaAlbumArtista().get(albumActual).getNombre());
       txtAlbumConsultar.setText(cancion.getMapaCancionAlbum().get(cancion).getNombre());
       txtDuracionConsultar.setText(cancion.getDuracion());
       txtAutorConsultar.setText(cancion.getAutor());
       txtGrabacionConsultar.setText(Integer.toString(cancion.getAnioGrabacion()));
    }
    
    //Obtiene los datos de una canción y los muestra en las cajas de texto respectivas
    private void editarInfoCancion(Cancion cancion){
       txtNumeroCancion.setText(Integer.toString(cancion.getNumero()));
       txtTituloCancion.setText(cancion.getTitulo());
       cmbAlbumes.setSelectedItem(cancion.getMapaCancionAlbum().get(cancion).getNombre());
       txtDuracion.setText(cancion.getDuracion());
       txtAutor.setText(cancion.getAutor());
       txtGrabacion.setText(Integer.toString(cancion.getAnioGrabacion()));
    }
    
    private void agregarCancion(Album album){
        if (txtNumeroCancion.getText().isEmpty() || 
            txtTituloCancion.getText().isEmpty() || 
            txtAutor.getText().isEmpty() ||
            txtGrabacion.getText().isEmpty() || 
            cmbAlbumes.getSelectedItem() == null ||
            txtDuracion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Error: Se deben llenar todos los campos requeridos.", "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Cancion cancion = new Cancion(
        Integer.parseInt(txtNumeroCancion.getText()),
        txtTituloCancion.getText(),
        txtDuracion.getText(),
        Integer.parseInt(txtGrabacion.getText()),
        txtAutor.getText());
        album.agregarCancion(cancion);
    }
    
    private void eliminarCancion(Cancion cancion){
        albumActual.eliminarCancion(cancion);
    }
    
    private void modificarCancion(Cancion cancion){
        if (txtNumeroCancion.getText().isEmpty() || 
            txtTituloCancion.getText().isEmpty() || 
            txtAutor.getText().isEmpty() ||
            txtGrabacion.getText().isEmpty() || 
            cmbAlbumes.getSelectedItem() == null ||
            txtDuracion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Error: Se deben llenar todos los campos requeridos.", "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        albumAnterior.eliminarCancion(cancion);
        cancion.setNumero(Integer.parseInt(txtNumeroCancion.getText()));
        cancion.setTitulo(txtTituloCancion.getText());
        cancion.setDuracion(txtDuracion.getText());
        cancion.setAutor(txtAutor.getText());
        cancion.setAnioGrabacion(Integer.parseInt(txtGrabacion.getText()));
        albumActual.agregarCancion(cancion);
    }
   
    //Deshabilita las cajas de texto para prevenir cambios en los datos
    private void deshabilitarCajas(){
        txtTituloCancionConsultar.setEditable(false);
        txtNumeroCancionConsultar.setEditable(false);
    }
    
    //Habilita las cajas de texto para agregar datos
    private void habilitarCajas(){
        txtTituloCancionConsultar.setEditable(true);
        txtNumeroCancionConsultar.setEditable(true);
    }
    
    //Limpia las cajas de texto
    private void limpiarCajas(){
        txtTituloCancionConsultar.setText("");
        txtAlbumConsultar.setText("");
        txtNumeroCancionConsultar.setText("");
        txtNombreArtistaConsultar.setText("");
        txtDuracionConsultar.setText("");
        txtAutorConsultar.setText("");
        txtGrabacionConsultar.setText("");
        txtTituloCancion.setText("");
        txtNumeroCancion.setText("");
        txtDuracion.setText("");
        txtAutor.setText("");
        txtGrabacion.setText("");
        cmbAlbumes.setSelectedItem(null);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogCanciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogCanciones dialog = new dialogCanciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAceptar;
    private javax.swing.JToggleButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbAlbumes;
    private javax.swing.JInternalFrame frameEditarCancion;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lstCanciones;
    private javax.swing.JLayeredPane paneInfoCancion;
    private javax.swing.JTextField txtAlbumConsultar;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAutorConsultar;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtDuracionConsultar;
    private javax.swing.JTextField txtGrabacion;
    private javax.swing.JTextField txtGrabacionConsultar;
    private javax.swing.JTextField txtNombreArtistaConsultar;
    private javax.swing.JTextField txtNumeroCancion;
    private javax.swing.JTextField txtNumeroCancionConsultar;
    private javax.swing.JTextField txtTituloCancion;
    private javax.swing.JTextField txtTituloCancionConsultar;
    // End of variables declaration//GEN-END:variables
}
