/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pantallas;

import Logica.Utilitario;
import Modelos.Album;
import Modelos.Artista;
import Modelos.Genero;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class dialogAlbumes extends javax.swing.JDialog {
   
    DefaultListModel modeloListaAlbumes = new DefaultListModel();
    
    //Variable para verificar si el usuario está usando el botón "Modificar"
    private boolean modificando = false; 
    
    //Variable de instancia para almacenar el Artista actual
    private Album albumActual;
    private Artista artistaActual;
    private Artista artistaAnterior;
    

    /**
     * Creates new form dialogArtistas
     */
    public dialogAlbumes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        lstAlbumes.setModel(modeloListaAlbumes);
        actualizarListaAlbumes();
        limpiarCajas();
        jInternalFrame1.setVisible(false);
        
    }

    private dialogAlbumes(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstAlbumes = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        panelInfoAlbum = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroAlbumConsultar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreAlbumConsultar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtArtistaAlbumConsultar = new javax.swing.JTextField();
        txtGeneroAlbumConsultar = new javax.swing.JTextField();
        txtTipoAlbumConsultar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadCanciones = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPublicacionConsultar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDiscograficaConsultar = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnCerrar = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreAlbum = new javax.swing.JTextField();
        comboGenero = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtNumeroAlbum = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbArtistas = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPublicacion = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        txtDiscografica = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(856, 638));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 1080, -1, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnInsertar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnInsertar.setPreferredSize(new java.awt.Dimension(98, 23));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -60, 15, 1190));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(98, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 98, -1));

        lstAlbumes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAlbumes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAlbumesMouseClicked(evt);
            }
        });
        lstAlbumes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAlbumesValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstAlbumes);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 275, 157));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Albumes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 275, -1));

        panelInfoAlbum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Género");

        txtNumeroAlbumConsultar.setEditable(false);
        txtNumeroAlbumConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroAlbumConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroAlbumConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAlbumConsultarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Artista del  Album");

        txtNombreAlbumConsultar.setEditable(false);
        txtNombreAlbumConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreAlbumConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreAlbumConsultar.setPreferredSize(new java.awt.Dimension(135, 22));
        txtNombreAlbumConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlbumConsultarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Número");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtArtistaAlbumConsultar.setEditable(false);
        txtArtistaAlbumConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtArtistaAlbumConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArtistaAlbumConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistaAlbumConsultarActionPerformed(evt);
            }
        });

        txtGeneroAlbumConsultar.setEditable(false);
        txtGeneroAlbumConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtGeneroAlbumConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTipoAlbumConsultar.setEditable(false);
        txtTipoAlbumConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtTipoAlbumConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoAlbumConsultar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTipoAlbumConsultar.setPreferredSize(new java.awt.Dimension(122, 22));
        txtTipoAlbumConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoAlbumConsultarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tipo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cantidad de Canciones");

        txtCantidadCanciones.setEditable(false);
        txtCantidadCanciones.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidadCanciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadCancionesActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Publicación");

        txtPublicacionConsultar.setEditable(false);
        txtPublicacionConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtPublicacionConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPublicacionConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublicacionConsultarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Discográfica");

        txtDiscograficaConsultar.setEditable(false);
        txtDiscograficaConsultar.setBackground(new java.awt.Color(255, 255, 255));
        txtDiscograficaConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscograficaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscograficaConsultarActionPerformed(evt);
            }
        });

        panelInfoAlbum.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtNumeroAlbumConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtNombreAlbumConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtArtistaAlbumConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtGeneroAlbumConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtTipoAlbumConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtCantidadCanciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtPublicacionConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelInfoAlbum.setLayer(txtDiscograficaConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelInfoAlbumLayout = new javax.swing.GroupLayout(panelInfoAlbum);
        panelInfoAlbum.setLayout(panelInfoAlbumLayout);
        panelInfoAlbumLayout.setHorizontalGroup(
            panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArtistaAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                        .addComponent(txtNumeroAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                        .addComponent(txtGeneroAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPublicacionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiscograficaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelInfoAlbumLayout.setVerticalGroup(
            panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtArtistaAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)))
                .addGap(6, 6, 6)
                .addGroup(panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoAlbumLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGeneroAlbumConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPublicacionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscograficaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtCantidadCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelInfoAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 460, 290));

        jInternalFrame1.setVisible(true);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tipo");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Género");

        txtNombreAlbum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreAlbum.setPreferredSize(new java.awt.Dimension(135, 22));
        txtNombreAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlbumActionPerformed(evt);
            }
        });

        for (Genero genero: Utilitario.listaGeneros) {
            comboGenero.addItem(genero.getNombre());
        }

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Publicación");

        txtNumeroAlbum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAlbumActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Número");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Discográfica");

        for (Artista item : Utilitario.listaArtistas){
            cmbArtistas.addItem(item.getNombre());
        }

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Artista del  Album");

        txtPublicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublicacionActionPerformed(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudio", "En Vivo", "EP", "Recopilatorio", "Sencillo", "Desconocido" }));
        comboTipo.setSelectedItem(null);
        comboTipo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        txtDiscografica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscografica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscograficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(txtNumeroAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(cmbArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(14, 14, 14)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        jPanel1.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Eliminar artista seleccionado de la lista
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        artistaSeleccionado();
        eliminarAlbum(albumActual);
        actualizarListaAlbumes();
        limpiarCajas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreAlbumConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlbumConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlbumConsultarActionPerformed
    
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        modificando = false;
        limpiarCajas();
        panelInfoAlbum.setVisible(false);
        jInternalFrame1.setVisible(true);
        cmbArtistas.setEnabled(true);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificando = true;
        artistaAnterior();     
        panelInfoAlbum.setVisible(false);
        jInternalFrame1.setVisible(true);
        cmbArtistas.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtNumeroAlbumConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAlbumConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAlbumConsultarActionPerformed

    private void lstAlbumesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAlbumesValueChanged
        
    }//GEN-LAST:event_lstAlbumesValueChanged

    private void txtCantidadCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCancionesActionPerformed

    private void lstAlbumesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAlbumesMouseClicked
        albumSeleccionado();
        obtenerInfoAlbum(albumActual);
        editarInfoAlbum(albumActual);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_lstAlbumesMouseClicked

    private void txtArtistaAlbumConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistaAlbumConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaAlbumConsultarActionPerformed

    private void txtTipoAlbumConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoAlbumConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoAlbumConsultarActionPerformed

    private void txtPublicacionConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublicacionConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublicacionConsultarActionPerformed

    private void txtDiscograficaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscograficaConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscograficaConsultarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        jInternalFrame1.setVisible(false);
        panelInfoAlbum.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtDiscograficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscograficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscograficaActionPerformed

    private void txtPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublicacionActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        artistaSeleccionado();
        albumSeleccionado();
        if (modificando == true) { //Verifica si el usuario está usando el botón de modificar
            modificarAlbum(albumActual);
        } else {
            agregarAlbum(artistaActual);
        }
        actualizarListaAlbumes();
        modificando = false;
        jInternalFrame1.setVisible(false);
        panelInfoAlbum.setVisible(true);
        obtenerInfoAlbum(albumActual);
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNumeroAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAlbumActionPerformed

    private void txtNombreAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlbumActionPerformed

    
    
    
    //Actualiza la lista en la interfaz sin necesidad de cerrar la ventana, y que pueda ser invocado cuando sea necesario
    private void actualizarListaAlbumes(){
        modeloListaAlbumes.clear(); //Limpiar la lista visualmente antes de volver a cargarla, evitando el duplicado visual de informacion
        for (Artista artista : Utilitario.listaArtistas) {
            modeloListaAlbumes.addAll(artista.generarListaAlbumes());
        }
    }
    
    //Toma el indice seleccionado de la lista Albumes
    private void albumSeleccionado(){
        String nombreAlbum = lstAlbumes.getSelectedValue();
        if (nombreAlbum != null) {
            for (Artista artista : Utilitario.listaArtistas) {
                for (Album album : artista.getListaAlbumes()) {
                    if (album.getNombre().equals(nombreAlbum)) {
                    this.albumActual = album;
                    }
                }
            }
        }
    }
    
    //Toma el indice seleccionado del ComboBox Artistas
    private void artistaSeleccionado(){
        int indiceArtista = cmbArtistas.getSelectedIndex();
        if (indiceArtista != -1){
            Artista artista = Utilitario.listaArtistas.get(indiceArtista);
            this.artistaActual = artista;
        }
    }
    
    //Toma el indice seleccionado del ComboBox Artistas para guardarlo en una variable temporal
    private void artistaAnterior(){
        int indiceArtista = cmbArtistas.getSelectedIndex();
        if (indiceArtista != -1){
            Artista artista = Utilitario.listaArtistas.get(indiceArtista);
            this.artistaAnterior = artista;
        }
    }
    
    //Obtiene los datos de un album, y los muestra en las cajas de texto respectivas
    private void obtenerInfoAlbum(Album album){
       if (albumActual != null) {
            txtNumeroAlbumConsultar.setText(Integer.toString(album.getNumero()));
            txtNombreAlbumConsultar.setText(album.getNombre());
            txtCantidadCanciones.setText(Integer.toString(album.getCantidadCanciones()));
            txtArtistaAlbumConsultar.setText(album.getMapaAlbumArtista().get(album).getNombre());
            txtGeneroAlbumConsultar.setText(album.getGenero().getNombre());
            txtTipoAlbumConsultar.setText(album.getTipo());
            txtPublicacionConsultar.setText(album.getPublicacion());
            txtDiscograficaConsultar.setText(album.getDiscografica());
        }
       
    }
    
    private void editarInfoAlbum(Album album){
       txtNumeroAlbum.setText(Integer.toString(album.getNumero()));
       txtNombreAlbum.setText(album.getNombre());
       txtCantidadCanciones.setText(Integer.toString(album.getCantidadCanciones()));
       cmbArtistas.setSelectedItem(album.getMapaAlbumArtista().get(album).getNombre());
       comboGenero.setSelectedItem(album.getGenero().getNombre());
       comboTipo.setSelectedItem(album.getTipo());
       txtPublicacion.setText(album.getPublicacion());
       txtDiscografica.setText(album.getDiscografica());
    }
    
    private void agregarAlbum(Artista artista){
        Album album = new Album(
        Integer.parseInt(txtNumeroAlbum.getText()),
        txtNombreAlbum.getText(),
        (comboTipo.getSelectedIndex()+1), 
        txtPublicacion.getText(),
        txtDiscografica.getText());
        Genero generoSeleccionado = obtenerGenero();
        if (!artistaActual.getListaGeneros().contains(generoSeleccionado)) {
            JOptionPane.showMessageDialog(rootPane, "Error: El artista no pertenece al género seleccionado.", "Género No Encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            artista.agregarAlbum(album);
            Utilitario.asignarGeneroAlbum(artistaActual, generoSeleccionado, album);
        }
    }
    
    private void eliminarAlbum(Album album){
        artistaActual.eliminarAlbum(album);
    }
    
    private void modificarAlbum(Album album){
        album.setNumero(Integer.parseInt(txtNumeroAlbumConsultar.getText()));
        album.setNombre(txtNombreAlbumConsultar.getText());
        album.setTipo((comboTipo.getSelectedIndex()+1));
        album.setPublicacion(txtPublicacion.getText());
        album.setDiscografica(txtDiscografica.getText());
        Genero generoSeleccionado = obtenerGenero();
        if (!artistaActual.getListaGeneros().contains(generoSeleccionado)) {
            JOptionPane.showMessageDialog(rootPane, "Error: El artista no pertenece al género seleccionado.", "Género No Encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            Utilitario.asignarGeneroAlbum(artistaActual, generoSeleccionado, album);
        }
    }
    
    private Genero obtenerGenero(){
        Object nombreGenero = comboGenero.getSelectedItem();
        for (Genero genero : Utilitario.listaGeneros) {
            if (genero.getNombre().equals(nombreGenero)) {
                return genero;
            }
        }
        return null;
    }
    
    //Limpia las cajas de texto
    private void limpiarCajas(){
        txtNombreAlbumConsultar.setText("");
        txtNumeroAlbumConsultar.setText("");
        txtArtistaAlbumConsultar.setText("");
        txtGeneroAlbumConsultar.setText("");
        txtPublicacionConsultar.setText("");
        txtDiscograficaConsultar.setText("");
        txtCantidadCanciones.setText("");
        txtGeneroAlbumConsultar.setText("");
        txtNombreAlbum.setText("");
        txtNumeroAlbum.setText("");
        txtPublicacion.setText("");
        txtDiscografica.setText("");
        cmbArtistas.setSelectedItem(null);
        comboGenero.setSelectedItem(null);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogAlbumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogAlbumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogAlbumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogAlbumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogAlbumes dialog = new dialogAlbumes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAceptar;
    private javax.swing.JToggleButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbArtistas;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lstAlbumes;
    private javax.swing.JLayeredPane panelInfoAlbum;
    private javax.swing.JTextField txtArtistaAlbumConsultar;
    private javax.swing.JTextField txtCantidadCanciones;
    private javax.swing.JTextField txtDiscografica;
    private javax.swing.JTextField txtDiscograficaConsultar;
    private javax.swing.JTextField txtGeneroAlbumConsultar;
    private javax.swing.JTextField txtNombreAlbum;
    private javax.swing.JTextField txtNombreAlbumConsultar;
    private javax.swing.JTextField txtNumeroAlbum;
    private javax.swing.JTextField txtNumeroAlbumConsultar;
    private javax.swing.JTextField txtPublicacion;
    private javax.swing.JTextField txtPublicacionConsultar;
    private javax.swing.JTextField txtTipoAlbumConsultar;
    // End of variables declaration//GEN-END:variables
}
